# _config.yml
title: onlymanes Blog
description: A personal blog about life & code
url: "https://onlymanes.ai"
baseurl: "/about"

theme: minima
# remote_theme: pages-themes/minima@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag

<meta http-equiv="refresh" content="0; url=/about/">
echo "onlymanes.ai" > CNAME
