title: onlymanes Blog
url: "https://onlymanes.ai"
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      head: |
  <!-- theme¡¯s main.css is already in <head>.
       adding link again puts our file *after* it -->
  <link rel="stylesheet" href="{{ '/assets/css/custom.css' | relative_url }}">


include:
  - _includes/footer.html