title: onlymanes Blog
url: "https://onlymanes.ai"
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      head: |           # ¡û this line ends with a pipe
        <link rel="stylesheet" href="{{ '/assets/css/custom.css' | relative_url }}">
        # ¡ü every line inside the multi?line value
        #   must be indented at least two spaces more
        #   than ¡°head: |¡±

include:
  - _includes/footer.html