# _config.yml
title: onlymanes Blog
description: A personal blog about life & code
url: "https://onlymanes.ai"
baseurl: ""
url: "https://onlymanes.ai"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      head: |
        <link rel="stylesheet" href="/assets/css/custom.css">