include:
  - assets/img/cover.jpg
  - _includes/footer.html
baseurl: ""
url: "https://onlymanes.ai"
plugins:
  - jekyll-sitemap
  - jekyll-feed
defaults:
  - scope:
      path: ""
    values:
      layout: default