title: onlymanes Blog
url: "https://onlymanes.ai"
baseurl: ""

defaults:
  - scope:
      path: ""
    values:
      head: |
        <link rel="stylesheet" href="{{ '/assets/css/custom.css' | relative_url }}"

include:
  - _includes/footer.html