title: onlymanes Blog
description: Personal blog sharing creative ideas
baseurl: /
url: https://onlymanes.ai

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - node_modules
  - Gemfile.lock
  - vendor